### ISSUE TITLE
Right clicking

### ISSUE THREAD

**Issue by PluginIssueTrackingFTW** [boomboompower/ThrowingTNT#4]
When I right click in mid air and right click tnt nothing throws. Not sure if this intended or not but all I know is it works if I left click (attack/hit).

@boomboompower please respond!

**Comment by boomboompower** [comment]
@PluginIssueTrackingFTW Yes this is a confirmed bug, I have been attempting to build a workaround for it but unfortunately haven't been successful. I'll notify you when this is fixed, until then this issue will remain open

**Comment by boomboompower** [comment]
This repository is outdated. Will not fix (even if we could)
